/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package kr.co.vcnc.haeinsa.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RowState implements org.apache.thrift.TEnum {
  STABLE(1),
  PREWRITTEN(2),
  ABORTED(3),
  COMMITTED(4);

  private final int value;

  private RowState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RowState findByValue(int value) { 
    switch (value) {
      case 1:
        return STABLE;
      case 2:
        return PREWRITTEN;
      case 3:
        return ABORTED;
      case 4:
        return COMMITTED;
      default:
        return null;
    }
  }
}
